### ISSUE TITLE
issue summary, files summary table too scrunched and more lines long

### ISSUE THREAD

**Issue by YesCT** [unicorn-fail/dreditor#69]
without dreditor table is like:
![filessummary-nodreditor](https://f.cloud.github.com/assets/1970586/1508638/73aee412-4a0d-11e3-874b-a77dba1a3c08.png)

with dreditor, the table is more narrow, the lines wrap, and the table gets longer
![filessummary-withdreditor](https://f.cloud.github.com/assets/1970586/1508637/73a58660-4a0d-11e3-8c09-b8cdc10ae371.png)

make the table wider. (which will make it shorter)

**Comment by sun** [comment]
This should not be addressed in Dreditor but directly on d.o instead, since the native/original table uses inappropriate styling already (should be `width: 100%;`).

As a temporary workaround, you can use the _drupal.org unleashed_ user style (which wasn't updated for D7 yet, but still appears to work).

**Comment by markhalliwell** [comment]
This actually was already fixed in #56.

**Comment by sun** [comment]
Perhaps I misunderstood this issue? — If so, I'd like to apologize for that.

However, to clarify:  General layout/styling issues of drupal.org should never be corrected in Dreditor.

Dreditor exists to _enhance_ the user experience for power users, but _not_ to fix general styling issues.  By correcting such issues in Dreditor, the issue still exists for the 99.9% other users of drupal.org.  If all power users suddenly do not see an issue anymore, then no one will fix drupal.org for the vast majority of regular users.

The only exception to this rule are drupal.org styles and behaviors that exist on purpose — for example, the fact that issue tags are being collapsed has been an intentional decision, since there were too many novice users who entered tons of stupid tags, so they're hidden/collapsed by default, and only Dreditor exposes them directly for power users. (currently broken; issue/comment form adjustments haven't been updated yet)

**Comment by markhalliwell** [comment]
No you have not misunderstood and I do agree that Dreditor shouldn't be styling "d.o fixes"... however:

The styling and markup manipulation for file tables was added because of the D7 upgrade. The reason this exists currently is mainly to initially prototype the changes suggested in https://drupal.org/node/2107101 (which was also discussed and agreed upon in person at BADCamp). We know that these changes only affect those that use Dreditor, which is the whole point. We need people to provide feedback and/or make adjustments prior to ultimately migrating these changes back into d.o.

The reason for the table width and selector changes in #56 was due to sticky headers being removed from d.o file tables. I cannot seem to find that issue, perhaps @Cottser can remember it.

**Comment by star-szr** [comment]
Yup, it had a very creative issue title :) https://drupal.org/node/2125583
